/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oltas;

import java.util.ArrayList;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Axmart
 */
public class Gyerekek extends javax.swing.JFrame {

    public static ArrayList<Gyerek> GyerekList;
    DefaultTableModel model;
    
    /**
     * Creates new form JFNyilvantarto
     */
    public Gyerekek() {
        initComponents();
        this.model = (DefaultTableModel)jTbl_gyerekAdatok.getModel();
        GyerekList = Gyerek.Beolvasas();
        insertTable();
        
        
    }
    private static final Logger LOG = Logger.getLogger(Gyerekek.class.getName());

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtn_ujGyerek = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_gyerekAdatok = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxta_oltasok = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxt_fizetettOsszeg = new javax.swing.JTextField();
        jTxt_oltasokDarabszama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxt_Azonosito = new javax.swing.JTextField();
        jTxt_Nev = new javax.swing.JTextField();
        jTxt_ApjaNeve = new javax.swing.JTextField();
        jTxt_anyjaNeve = new javax.swing.JTextField();
        jBtn_modositas = new javax.swing.JButton();
        jlbl_hiba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Vedooltasok nyilvantartasa");

        jbtn_ujGyerek.setText("Uj gyerek adatainak felvetele");
        jbtn_ujGyerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ujGyerekActionPerformed(evt);
            }
        });

        jTbl_gyerekAdatok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Azon", "Nev", "Apja neve", "Anyja neve", "TAJ-szam", "Szuletett"
            }
        ));
        jTbl_gyerekAdatok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_gyerekAdatokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTbl_gyerekAdatok);

        jLabel2.setText("A kivalasztott gyerek adatainak modositasa");

        jLabel3.setText("A kivalasztott gyerek oltasai:");

        jTxta_oltasok.setColumns(20);
        jTxta_oltasok.setRows(5);
        jScrollPane2.setViewportView(jTxta_oltasok);

        jLabel4.setText("Oltasokert fizetett osszeg");

        jLabel5.setText("Beadott oltasok darabszama");

        jLabel6.setText("Azonosito");

        jLabel7.setText("Nev: ");

        jLabel8.setText("Apja neve:");

        jLabel9.setText("Anyja neve");

        jTxt_Azonosito.setEnabled(false);

        jBtn_modositas.setText("Modositas");
        jBtn_modositas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_modositasActionPerformed(evt);
            }
        });

        jlbl_hiba.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(jbtn_ujGyerek, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn_modositas, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTxt_ApjaNeve))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTxt_Azonosito)
                                                .addComponent(jTxt_Nev, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTxt_anyjaNeve)))
                                    .addComponent(jlbl_hiba))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxt_fizetettOsszeg)
                                    .addComponent(jTxt_oltasokDarabszama, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_ujGyerek, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTxt_Azonosito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTxt_Nev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTxt_ApjaNeve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxt_fizetettOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTxt_anyjaNeve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTxt_oltasokDarabszama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbl_hiba)
                        .addGap(13, 13, 13)
                        .addComponent(jBtn_modositas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jbtn_ujGyerek.getAccessibleContext().setAccessibleName("jbtn_ujGyerek");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTbl_gyerekAdatokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_gyerekAdatokMouseClicked
        // TODO add your handling code here:
        int sorIndex = jTbl_gyerekAdatok.getSelectedRow();
        jTxt_Azonosito.setText(String.valueOf( GyerekList.get(sorIndex).getId()));
        jTxt_Nev.setText(GyerekList.get(sorIndex).getNev());
        jTxt_ApjaNeve.setText(GyerekList.get(sorIndex).getApja());
        jTxt_anyjaNeve.setText(GyerekList.get(sorIndex).getAnyja());
        
        ArrayList<Oltas> oltasok = Oltas.Beolvasas(GyerekList.get(sorIndex).getId());
        
        String oltasokFelsorolas = "";
        int osszeg = 0;
        int darab = 0;
        
        for (Oltas oltas : oltasok) {
            
            oltasokFelsorolas+= oltas.getElnevezes()+"\n";
            osszeg += oltas.getFizetendo();
            darab++;
        }
        
        jTxta_oltasok.setText(oltasokFelsorolas); 
        jTxt_fizetettOsszeg.setText(String.valueOf(osszeg));
        jTxt_oltasokDarabszama.setText(String.valueOf(darab));
        
        
    }//GEN-LAST:event_jTbl_gyerekAdatokMouseClicked

    private void jBtn_modositasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_modositasActionPerformed
        // TODO add your handling code here:
        jlbl_hiba.setText("");
        if (jTxt_Nev.getText().trim().length() < 1 || jTxt_ApjaNeve.getText().trim().length() < 1 || jTxt_anyjaNeve.getText().trim().length() < 1) {
            
            jlbl_hiba.setText("egyik mezo sem lehet ures");
        }else   
        if (jTxt_Nev.getText().trim().length() > 30 || jTxt_ApjaNeve.getText().trim().length() > 30 || jTxt_anyjaNeve.getText().trim().length() > 30) {
            jlbl_hiba.setText("egyik mezo sem lehet tobb 30 karakternel");
        }else{
            Gyerek modositando = new Gyerek(jTbl_gyerekAdatok.getSelectedRow()+1, jTxt_Nev.getText(), jTxt_ApjaNeve.getText(), jTxt_anyjaNeve.getText(), "", null);
            Gyerek.Modositas(modositando);
            GyerekList = Gyerek.Beolvasas();
            insertTable();
            
        }
        
        
        
        
        
    }//GEN-LAST:event_jBtn_modositasActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        GyerekList = Gyerek.Beolvasas();
        insertTable();
    }//GEN-LAST:event_formFocusGained

    private void jbtn_ujGyerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ujGyerekActionPerformed
        // TODO add your handling code here:
        
        Ujgyerek ujgyerekForm = new Ujgyerek();
        ujgyerekForm.show();
        
    }//GEN-LAST:event_jbtn_ujGyerekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gyerekek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gyerekek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gyerekek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gyerekek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gyerekek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_modositas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTbl_gyerekAdatok;
    private javax.swing.JTextField jTxt_ApjaNeve;
    private javax.swing.JTextField jTxt_Azonosito;
    private javax.swing.JTextField jTxt_Nev;
    private javax.swing.JTextField jTxt_anyjaNeve;
    private javax.swing.JTextField jTxt_fizetettOsszeg;
    private javax.swing.JTextField jTxt_oltasokDarabszama;
    private javax.swing.JTextArea jTxta_oltasok;
    private javax.swing.JButton jbtn_ujGyerek;
    private javax.swing.JLabel jlbl_hiba;
    // End of variables declaration//GEN-END:variables

    private void insertTable() {
        
        int sorokSzama= model.getRowCount();
        for (int i = sorokSzama; i > 0; i--) {
            model.removeRow(i-1);
        }
        
        for (Gyerek gyerek : GyerekList) {
            
            model.addRow(new Object[]{gyerek.getId(),gyerek.getNev(),gyerek.getApja(),gyerek.getAnyja(),gyerek.getTajszam(),gyerek.getSzuletett()});
            
        }
        
        
    }
}
