/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oltas;

import java.sql.Date;

/**
 *
 * @author Axmart
 */
public class Ujgyerek extends javax.swing.JFrame {

    /**
     * Creates new form Ujgyerek
     */
    public Ujgyerek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxt_Nev = new javax.swing.JTextField();
        jTxt_Apja = new javax.swing.JTextField();
        jTxt_Anyja = new javax.swing.JTextField();
        jTxt_TajSzam = new javax.swing.JTextField();
        jTxt_Szuletett = new javax.swing.JTextField();
        jbtn_rogzit = new javax.swing.JButton();
        jLbl_hiba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nev");

        jLabel2.setText("Apja neve");

        jLabel3.setText("Anyja neve");

        jLabel4.setText("TAJ-szam");

        jLabel5.setText("Szuletett");

        jbtn_rogzit.setText("Rogzites");
        jbtn_rogzit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_rogzitActionPerformed(evt);
            }
        });

        jLbl_hiba.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtn_rogzit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxt_Nev)
                            .addComponent(jTxt_Szuletett, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jTxt_TajSzam)
                            .addComponent(jTxt_Anyja)
                            .addComponent(jTxt_Apja)))
                    .addComponent(jLbl_hiba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxt_Nev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxt_Apja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxt_Anyja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxt_TajSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxt_Szuletett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLbl_hiba)
                .addGap(18, 18, 18)
                .addComponent(jbtn_rogzit)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_rogzitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_rogzitActionPerformed
        // TODO add your handling code here:
        
        if (jTxt_Nev.getText().trim().length() < 1 || jTxt_Apja.getText().trim().length() < 1 || jTxt_Anyja.getText().trim().length() < 1 || jTxt_TajSzam.getText().trim().length() < 1 || jTxt_Szuletett.getText().trim().length() < 1 ) {
            
            jLbl_hiba.setText("egyik mezo sem lehet ures");
        }else   
        if (jTxt_Nev.getText().trim().length() > 30 || jTxt_Apja.getText().trim().length() > 30 || jTxt_Anyja.getText().trim().length() > 30) {
            jLbl_hiba.setText("egyik nev sem lehet tobb 30 karakternel");
        }if (jTxt_TajSzam.getText().trim().length() < 9 ) {
            jLbl_hiba.setText("a taj szam sem lehet tobb 9 karakternel");
        }
        else{
            Gyerek ujGyerek = new Gyerek(0, jTxt_Nev.getText(), jTxt_Apja.getText(), jTxt_Anyja.getText(), jTxt_TajSzam.getText(), Date.valueOf(jTxt_Szuletett.getText()));
            Gyerek.Rogzites(ujGyerek);
            this.dispose();
        }
        
        
        
        
    }//GEN-LAST:event_jbtn_rogzitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ujgyerek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ujgyerek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ujgyerek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ujgyerek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ujgyerek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbl_hiba;
    private javax.swing.JTextField jTxt_Anyja;
    private javax.swing.JTextField jTxt_Apja;
    private javax.swing.JTextField jTxt_Nev;
    private javax.swing.JTextField jTxt_Szuletett;
    private javax.swing.JTextField jTxt_TajSzam;
    private javax.swing.JButton jbtn_rogzit;
    // End of variables declaration//GEN-END:variables
}
